### ISSUE TITLE
Missing comma between pcall() arguments

### ISSUE THREAD

**Issue by craigbarnes** [daurnimator/luacov-reporter-lcov#1]
On line 13 of `lcov.lua` there's a call to `pcall()`, but it's not actually protecting the call to `require` because there's no comma between the arguments:

https://github.com/daurnimator/luacov-reporter-lcov/blob/30dba8739996ec5a0bda038eead2f178a6a39819/luacov/reporter/lcov.lua#L13

If the module is installed, this results in:

```
> pcall(require "openssl.digest")
false   attempt to call a table value
```

...and the code then just takes the false branch and `md5sumhex` remains `nil`.

If the module *isn't* installed, it throws an [error](https://gitlab.com/craigbarnes/lua-gumbo/-/jobs/232805091):

```
/usr/local/share/lua/5.1/luacov/reporter/lcov.lua:13: module 'openssl.digest' not found:No LuaRocks module found for openssl.digest
	no field package.preload['openssl.digest']
	......
stack traceback:
	[C]: in function 'require'
	/usr/local/share/lua/5.1/luacov/reporter/lcov.lua:13: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/luacov/runner.lua:134: in function 'run_report'
	.../local/lib/luarocks/rocks/luacov/0.13.0-1/bin/luacov:99: in main chunk
```

The md5 dependency also isn't listed in the rockspec, but I guess that's because it's optional...?

[line 13]: https://github.com/daurnimator/luacov-reporter-lcov/blob/30dba8739996ec5a0bda038eead2f178a6a39819/luacov/reporter/lcov.lua#L13

**Comment by daurnimator** [comment]
> there's a call to `pcall()`, but it's not actually protecting the call to `require` because there's no comma between the arguments

Doh.
Did you want to send a quick PR?

> The md5 dependency also isn't listed in the rockspec, but I guess that's because it's optional...?

Correct.

**Comment by craigbarnes** [comment]
> Did you want to send a quick PR?

Sure. Opened as #2.

**Comment by daurnimator** [comment]
Fixed via #2

**Comment by 4O4** [comment]
@daurnimator can you publish on luarocks the version with this fix included? I've encountered this problem too

**Comment by daurnimator** [comment]
> @daurnimator can you publish on luarocks the version with this fix included? I've encountered this problem too

done.
